### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by Tux** [haje61/Tk-ITree#1]
https://github.com/haje61/Tk-ITree/blame/fbd18d3a344b346c5813199634325bc81c5707a4/lib/Tk/ITree.pm#L50

Then why call it Tk::ITree instead of Tk::Tree::DarkTheme or Tk::Tree::Dark ?

**Comment by haje61** [comment]
The name ITree is pretty arbitrarily chosen, and maybe not the best choice.
However, putting something with Dark in it would suggest it is only
meant for dark desktops, which it is not. It performs well in light
and dark desktop environments.

I'll stick with the name for now.

Best regards,
Hans
